

services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:      
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: bd_ejercicio1
      
    ports:
      - 5432:5432

    networks:
      - django_network

    volumes:
      - postgres_data:/var/lib/postgresql/postgres_data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=ff@correo.cl
      - PGADMIN_DEFAULT_PASSWORD=1234
      - PGADMIN_CONFIG_PROXY_X_HOST_COUNT= 1
      - PGADMIN_CONFIG_PROXY_X_PREFIX_COUNT= 1
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - django_network


volumes:
  postgres_data:

networks:
  django_network:
    driver: bridge

